//------------------------------------------------------------------------------------
// generators.mjs -- Part of RStellarScribe
//
// Write tools. Field names are taken from the shipped copy of Stellaris 4.1.7:
//
//   * decisions  <- common/decisions/example.txt        (Paradox's own schema stub)
//   * technology <- common/technology/000_documentation.txt
//   * civics     <- common/governments/civics/01_origins_non_playable.txt
//   * traditions <- common/traditions/00_logistics.txt
//   * events     <- events/biogenesis_bioship_events.txt and the `.name`/`.desc`/`.a`
//                   localisation key convention (5490 occurrences in vanilla)
//
// Every generator defaults to a dry run and returns the same file plan either way.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//------------------------------------------------------------------------------------

import {
  asciiKey,
  ENCODING_UTF8_BOM,
  escapeScriptString,
  finishGeneration,
  generatedFile,
  optionalString,
  requireArray,
  requireString,
  ToolError,
} from '../lib/generation.mjs';
import { renderLocalisationFile } from '../lib/localisation.mjs';
import {
  LOCALISATION_LANGUAGES,
  localisationPathFor,
  normaliseLanguage,
} from '../lib/paths.mjs';
import { checkScriptStructure } from '../lib/paradox.mjs';

export const SCRIPT_HEADER = (path, source) =>
  `# Generated by RStellarScribe for ${path}.\n# Field names follow the installed game's own files; see ${source}.\n\n`;

/**
 * The event type keywords Stellaris 4.4.6 uses as top-level blocks in `events/`.
 *
 * A namespace is NOT an event type. Writing `<namespace>_event = { ... }` makes the engine
 * report `Corrupt Event Table Entry` once per token in the block and register no event at
 * all - a live game test produced 20 such errors from one event before this list existed.
 */
export const EVENT_TYPES = new Set([
  'agreement_event',
  'astral_rift_event',
  'bypass_event',
  'country_event',
  'espionage_operation_event',
  'first_contact_event',
  'fleet_event',
  'leader_event',
  'observer_event',
  'planet_event',
  'pop_faction_event',
  'pop_group_event',
  'ship_event',
  'situation_event',
  'starbase_event',
  'system_event',
]);

// ------------------------------------------------------------------------------------
// shared helpers (exported for generators-content.mjs)
// ------------------------------------------------------------------------------------

/** Indent a raw script body by `depth` tabs and reject unbalanced input. */
export function blockBody(name, raw, depth = 1) {
  const text = String(raw ?? '').trim();
  if (text === '') return null;
  const structure = checkScriptStructure(text, `\`${name}\``);
  if (structure.errors.length > 0) {
    throw new ToolError(
      `the \`${name}\` block is not valid script:\n- ` +
        structure.errors.map((error) => `line ${error.line}: ${error.message}`).join('\n- '),
    );
  }
  const indent = '\t'.repeat(depth);
  return text
    .split('\n')
    .map((line) => (line.trim() === '' ? '' : indent + line.replace(/^\t+/, '')))
    .join('\n');
}

export function block(name, raw, depth = 1) {
  const body = blockBody(name, raw, depth + 1);
  const indent = '\t'.repeat(depth);
  if (body === null) return `${indent}${name} = { }`;
  return `${indent}${name} = {\n${body}\n${indent}}`;
}

export function blockFromLines(name, lines, depth = 1) {
  const indent = '\t'.repeat(depth);
  if (lines.length === 0) return `${indent}${name} = { }`;
  return `${indent}${name} = {\n${lines.map((line) => `${indent}\t${line}`).join('\n')}\n${indent}}`;
}

export function quoteList(values) {
  return values.map((value) => `"${escapeScriptString(value)}"`).join(' ');
}

export function assertLanguage(language) {
  const resolved = normaliseLanguage(language ?? 'english');
  if (!LOCALISATION_LANGUAGES.includes(resolved)) {
    throw new ToolError(`unknown language \`${language}\``);
  }
  return resolved;
}

export function localisationPlan({ language, path, entries, summary }) {
  return generatedFile(path, renderLocalisationFile({ language, entries }), {
    encoding: ENCODING_UTF8_BOM,
    summary,
  });
}

/** Definition keys must be lowercase ASCII: non-ASCII keys break script parsing. */
export function requireDefinitionKey(value, field) {
  const key = requireString(value, field);
  if (!/^[a-z0-9_.]+$/.test(key)) {
    throw new ToolError(
      `\`${field}\` must be a lowercase ASCII key (letters, digits, underscore, dot); received \`${key}\``,
    );
  }
  return key;
}

// ------------------------------------------------------------------------------------
// setup_stellaris_mod_skeleton
// ------------------------------------------------------------------------------------

export function setupStellarisModSkeleton(args = {}) {
  const modName = requireString(args.mod_name, 'mod_name');
  const prefix = asciiKey(optionalString(args.prefix) ?? optionalString(args.folder_name) ?? modName, {
    fallback: 'mymod',
  });
  const supportedVersion = optionalString(args.supported_version) ?? 'v4.1.*';
  const language = assertLanguage(args.language ?? 'english');
  const dryRun = args.dry_run !== false;
  const outputRoot = optionalString(args.output_root);

  const files = [
    generatedFile(
      'descriptor.mod',
      descriptorContent({ modName, supportedVersion, tags: args.tags }),
      { summary: 'Stellaris mod descriptor metadata' },
    ),
    generatedFile(
      `events/${prefix}_events.txt`,
      `${SCRIPT_HEADER(`events/${prefix}_events.txt`, 'events/')}namespace = ${prefix}\n\ncountry_event = {\n\tid = ${prefix}.1\n\ttitle = ${prefix}.1.name\n\tdesc = ${prefix}.1.desc\n\n\tis_triggered_only = yes\n\n\toption = {\n\t\tname = ${prefix}.1.a\n\t}\n}\n`,
      { summary: 'Starter event namespace and one triggered event' },
    ),
    generatedFile(
      `common/scripted_effects/${prefix}_scripted_effects.txt`,
      `${SCRIPT_HEADER(`common/scripted_effects/${prefix}_scripted_effects.txt`, 'common/scripted_effects/')}# Reusable effect blocks. Call one as `+"`"+`${prefix}_example_effect = yes`+"`"+`.\n${prefix}_example_effect = {\n\tset_country_flag = ${prefix}_example_flag\n}\n`,
      { summary: 'Starter scripted effects file' },
    ),
    generatedFile(
      `common/scripted_triggers/${prefix}_scripted_triggers.txt`,
      `${SCRIPT_HEADER(`common/scripted_triggers/${prefix}_scripted_triggers.txt`, 'common/scripted_triggers/')}${prefix}_example_trigger = {\n\thas_country_flag = ${prefix}_example_flag\n}\n`,
      { summary: 'Starter scripted triggers file' },
    ),
    generatedFile(
      `common/scripted_variables/${prefix}_scripted_variables.txt`,
      `${SCRIPT_HEADER(`common/scripted_variables/${prefix}_scripted_variables.txt`, 'common/scripted_variables/')}# `+"`"+`@`+"`"+` variables are file-local constants referenced as @${prefix}_base_cost.\n@${prefix}_base_cost = 100\n`,
      { summary: 'Starter scripted variables file' },
    ),
    generatedFile(
      `common/on_actions/${prefix}_on_actions.txt`,
      `${SCRIPT_HEADER(`common/on_actions/${prefix}_on_actions.txt`, 'common/on_actions/')}# on_action blocks accept only `+"`"+`events`+"`"+` and `+"`"+`random_events`+"`"+` (verified against 4.1.7).\non_game_start = {\n\tevents = {\n\t\t${prefix}.1\n\t}\n}\n`,
      { summary: 'Starter on_actions file that fires the starter event at game start' },
    ),
    localisationPlan({
      language,
      path: localisationPathFor(`${language}/${prefix}_core`, language),
      entries: [
        { key: `${prefix}.1.name`, value: `${modName}` },
        { key: `${prefix}.1.desc`, value: 'The first page is blank, and the writing is ours to do.' },
        { key: `${prefix}.1.a`, value: 'Then let us begin.' },
      ],
      summary: `Starter ${language} localisation for the starter event`,
    }),
  ];

  const result = finishGeneration({ dryRun, outputRoot, files });
  result.launcher_file = launcherContent({
    modName,
    supportedVersion,
    modRoot: outputRoot,
    tags: Array.isArray(args.tags) && args.tags.length > 0 ? args.tags : ['Gameplay'],
  });
  result.messages.push(
    'To make the mod visible in the launcher, save the `launcher_file` content as `<folder_name>.mod` in `Documents/Paradox Interactive/Stellaris/mod/`. This server never writes outside `output_root`.',
  );
  result.messages.push(
    `Localisation was written for \`${language}\` only. Stellaris has no fallback language: other languages will show the raw keys until you ship matching files.`,
  );
  return result;
}

function descriptorContent({ modName, supportedVersion, tags, version = '0.1' }) {
  const tagList = Array.isArray(tags) && tags.length > 0 ? tags : ['Gameplay'];
  return [
    `version="${escapeScriptString(version)}"`,
    'tags={',
    ...tagList.map((tag) => `\t"${escapeScriptString(tag)}"`),
    '}',
    `name="${escapeScriptString(modName)}"`,
    `supported_version="${escapeScriptString(supportedVersion)}"`,
    '',
  ].join('\n');
}

function launcherContent({ modName, supportedVersion, modRoot, version = '0.1', tags = ['Gameplay'] }) {
  const path = modRoot ? modRoot.replace(/\\/g, '/') : '<ABSOLUTE_MOD_ROOT_WITH_FORWARD_SLASHES>';
  const tagList = Array.isArray(tags) && tags.length > 0 ? tags : ['Gameplay'];
  return [
    `version="${escapeScriptString(version)}"`,
    'tags={',
    ...tagList.map((tag) => `\t"${escapeScriptString(tag)}"`),
    '}',
    `name="${escapeScriptString(modName)}"`,
    `supported_version="${escapeScriptString(supportedVersion)}"`,
    `path="${path}"`,
    '',
  ].join('\n');
}

// ------------------------------------------------------------------------------------
// generate_stellaris_mod_descriptor
// ------------------------------------------------------------------------------------

export function generateStellarisModDescriptor(args = {}) {
  const modName = requireString(args.mod_name, 'mod_name');
  const version = optionalString(args.version) ?? '0.1';
  const supportedVersion = optionalString(args.supported_version) ?? 'v4.1.*';
  const dependencies = Array.isArray(args.dependencies) ? args.dependencies : [];
  const replacePath = Array.isArray(args.replace_path) ? args.replace_path : [];
  const dryRun = args.dry_run !== false;
  const outputRoot = optionalString(args.output_root);

  const lines = [
    `version="${escapeScriptString(version)}"`,
    'tags={',
    ...((Array.isArray(args.tags) && args.tags.length > 0 ? args.tags : ['Gameplay']).map(
      (tag) => `\t"${escapeScriptString(tag)}"`,
    )),
    '}',
    `name="${escapeScriptString(modName)}"`,
    `supported_version="${escapeScriptString(supportedVersion)}"`,
  ];
  if (dependencies.length > 0) {
    lines.push('dependencies={', ...dependencies.map((dep) => `\t"${escapeScriptString(dep)}"`), '}');
  }
  if (replacePath.length > 0) {
    lines.push('replace_path={', ...replacePath.map((entry) => `\t"${escapeScriptString(entry)}"`), '}');
  }
  lines.push('', '');

  const files = [
    generatedFile('descriptor.mod', lines.join('\n'), { summary: 'Stellaris mod descriptor metadata' }),
  ];
  const result = finishGeneration({ dryRun, outputRoot, files });
  result.launcher_file = launcherContent({
    modName,
    supportedVersion,
    modRoot: outputRoot,
    version,
    tags: Array.isArray(args.tags) && args.tags.length > 0 ? args.tags : ['Gameplay'],
  });
  if (replacePath.length > 0) {
    result.messages.push(
      `\`replace_path\` is set for ${replacePath.join(', ')}. Caution: the field appears in no shipped 4.1.7 descriptor and in none of the 65 installed mod descriptors inspected for the knowledge base, so its Stellaris behaviour is unverified. If the engine honours it, the game ignores every vanilla file in those folders.`,
    );
  }
  result.messages.push(
    '`path` belongs in the launcher copy of the descriptor only; keeping it out of the mod-root copy avoids a stale path after the mod folder moves.',
  );
  return result;
}

// ------------------------------------------------------------------------------------
// generate_localisation_batch
// ------------------------------------------------------------------------------------

export function generateLocalisationBatch(args = {}) {
  const language = assertLanguage(args.language ?? 'english');
  const fileStem = requireString(args.file_stem, 'file_stem');
  const keyPrefix = optionalString(args.key_prefix) ?? '';
  const entries = requireArray(args.entries, 'entries');
  const includeDescriptions = args.include_descriptions !== false;
  const dryRun = args.dry_run !== false;
  const outputRoot = optionalString(args.output_root);

  const localisationEntries = [];
  for (const [index, entry] of entries.entries()) {
    const id = requireString(entry.id ?? entry.key, `entries[${index}].id`);
    if (!/^[A-Za-z0-9_.\-]+$/.test(id)) {
      throw new ToolError(
        `entries[${index}].id \`${id}\` must be ASCII: localisation keys stay ASCII even when the visible text is not`,
      );
    }
    const key = `${keyPrefix}${id}`;
    if (!/^[A-Za-z0-9_.\-]+$/.test(key)) {
      throw new ToolError(`entry key \`${key}\` must stay ASCII; only the visible text may be non-ASCII`);
    }
    localisationEntries.push({
      key,
      value: requireString(entry.title ?? entry.value, `entries[${index}].title`),
    });
    if (includeDescriptions && (entry.description ?? entry.desc)) {
      localisationEntries.push({ key: `${key}_desc`, value: String(entry.description ?? entry.desc) });
    }
    if (entry.effects) {
      localisationEntries.push({ key: `${key}_effects`, value: String(entry.effects) });
    }
  }

  const path = localisationPathFor(fileStem, language);
  const files = [
    localisationPlan({
      language,
      path,
      entries: localisationEntries,
      summary: `Stellaris ${language} localisation with ${localisationEntries.length} keys`,
    }),
  ];

  const result = finishGeneration({ dryRun, outputRoot, files });
  result.language = language;
  result.header = `l_${language}:`;
  result.key_count = localisationEntries.length;
  result.messages.push(
    `Written as UTF-8 with BOM with the header \`l_${language}:\`; both are required or the game ignores the file without a log entry.`,
  );
  return result;
}

// ------------------------------------------------------------------------------------
// generate_event_batch
// ------------------------------------------------------------------------------------

export function generateEventBatch(args = {}) {
  const namespace = asciiKey(requireString(args.namespace, 'namespace'), { fallback: 'mymod' });
  const events = requireArray(args.events, 'events');
  const language = assertLanguage(args.language ?? 'english');
  const withLocalisation = args.generate_localisation !== false;
  const dryRun = args.dry_run !== false;
  const outputRoot = optionalString(args.output_root);
  const fileName = optionalString(args.file_name) ?? `${namespace}_events`;

  const script = [];
  const localisationEntries = [];

  for (const [index, event] of events.entries()) {
    const suffix =
      event.id !== undefined && Number.isFinite(Number(event.id))
        ? String(Number(event.id))
        : String(index + 1);
    const id = `${namespace}.${suffix}`;
    const optionLetters = 'abcdefghijklmnopqrstuvwxyz';
    const options = Array.isArray(event.options) ? event.options : [];
    const optionEntries = [];
    const eventType = optionalString(event.event_type) ?? 'country_event';
    if (!EVENT_TYPES.has(eventType)) {
      throw new ToolError(
        `events[${index}].event_type \`${eventType}\` is not a Stellaris event type; expected one of ${[...EVENT_TYPES].join(', ')}`,
      );
    }

    const lines = [`${eventType} = {`];
    lines.push(`\tid = ${id}`);
    if (event.hide_window) {
      lines.push('\thide_window = yes');
    } else {
      lines.push(`\ttitle = ${id}.name`);
      const desc = event.desc;
      if (typeof desc === 'string' && desc.trim() !== '' && checkScriptStructure(desc).errors.length === 0 && /\btrigger\s*=|\btext\s*=/.test(desc)) {
        lines.push(block('desc', desc, 1));
      } else {
        lines.push(`\tdesc = ${id}.desc`);
      }
    }
    if (event.picture) lines.push(`\tpicture = ${optionalString(event.picture)}`);
    if (event.is_triggered_only !== false) lines.push('\tis_triggered_only = yes');
    if (event.fire_only_once) lines.push('\tfire_only_once = yes');
    if (event.trigger) lines.push(block('trigger', event.trigger, 1));
    if (event.mean_time_to_happen) lines.push(block('mean_time_to_happen', event.mean_time_to_happen, 1));
    if (event.weight_multiplier) lines.push(block('weight_multiplier', event.weight_multiplier, 1));
    if (event.immediate) lines.push(block('immediate', event.immediate, 1));
    if (event.after) lines.push(block('after', event.after, 1));
    if (event.abort_trigger) lines.push(block('abort_trigger', event.abort_trigger, 1));
    if (event.abort_effect) lines.push(block('abort_effect', event.abort_effect, 1));

    options.forEach((option, optionIndex) => {
      const letter = optionLetters[optionIndex] ?? `o${optionIndex + 1}`;
      const optionKey =
        option.key && String(option.key).includes('.') ? String(option.key) : `${id}.${letter}`;
      const optionLines = [`\toption = {`, `\t\tname = ${optionKey}`];
      if (option.trigger) {
        const body = blockBody('trigger', option.trigger, 3);
        optionLines.push('\t\ttrigger = {', body ?? '', '\t\t}');
      }
      if (option.allow) {
        const body = blockBody('allow', option.allow, 3);
        optionLines.push('\t\tallow = {', body ?? '', '\t\t}');
      }
      if (option.ai_chance) {
        const body = blockBody('ai_chance', option.ai_chance, 3);
        optionLines.push('\t\tai_chance = {', body ?? '', '\t\t}');
      }
      if (option.hidden_effect) {
        const body = blockBody('hidden_effect', option.hidden_effect, 3);
        optionLines.push('\t\thidden_effect = {', body ?? '', '\t\t}');
      }
      if (option.effect) {
        // Option effects are written DIRECTLY inside the option block. There is no
        // `effect = { }` key in Stellaris: across 12958 vanilla option blocks the
        // immediate child keys are name / hidden_effect / trigger / custom_tooltip /
        // owner / ai_chance / allow plus the effects themselves. Wrapping them in
        // `effect = { }` makes the engine look for a scripted effect called `effect`
        // and reports "Corrupt Event Table Entry" for every token that follows.
        const body = blockBody('option effects', option.effect, 2);
        if (body !== null) optionLines.push(body);
      }
      optionLines.push('\t}');
      lines.push(optionLines.join('\n'));

      if (withLocalisation) {
        optionEntries.push({
          key: optionKey,
          value: requireString(option.text ?? option.label ?? option.name, `events[${index}].options[${optionIndex}].text`),
        });
      }
    });

    lines.push('}');
    script.push(lines.join('\n'));

    if (withLocalisation && !event.hide_window) {
      localisationEntries.push({
        key: `${id}.name`,
        value: requireString(event.title, `events[${index}].title`),
      });
      localisationEntries.push({
        key: `${id}.desc`,
        value: requireString(event.description ?? event.text, `events[${index}].description`),
      });
      localisationEntries.push(...optionEntries);
    }
  }

  const cleanEntries = localisationEntries.filter((entry) => entry.value !== '');
  const scriptPath = `events/${fileName}.txt`;
  const content = `${SCRIPT_HEADER(scriptPath, 'events/')}namespace = ${namespace}\n\n${script.join('\n\n')}\n`;

  const structure = checkScriptStructure(content, scriptPath);
  if (structure.errors.length > 0) {
    throw new ToolError(
      `generated event script is invalid:\n- ` +
        structure.errors.map((error) => `line ${error.line}: ${error.message}`).join('\n- '),
    );
  }

  const files = [generatedFile(scriptPath, content, { summary: `${events.length} Stellaris event(s) in namespace ${namespace}` })];
  if (withLocalisation && cleanEntries.length > 0) {
    files.push(
      localisationPlan({
        language,
        path: localisationPathFor(`${language}/${namespace}_events`, language),
        entries: cleanEntries,
        summary: `Event localisation for namespace ${namespace}`,
      }),
    );
  }

  const result = finishGeneration({ dryRun, outputRoot, files });
  result.namespace = namespace;
  result.event_ids = events.map((_, index) =>
    `${namespace}.${events[index].id !== undefined && Number.isFinite(Number(events[index].id)) ? Number(events[index].id) : index + 1}`,
  );
  result.messages.push(
    'Option effects are written inline inside `option = { }`; there is no `effect = { }` key. Use `hidden_effect = { }` for effects the player must not see.',
  );
  result.messages.push(
    'Events without a `picture` load fine but the engine notes "has no pictures", and the event shows no art. Vanilla almost always sets one.',
  );
  result.messages.push(
    `Event localisation keys follow the vanilla convention \`<namespace>.<id>.name\`, \`.desc\` and \`.a\`/\`.b\`: ${result.event_ids.join(', ')}.`,
  );
  if (withLocalisation) {
    result.messages.push(
      `Only ${language} was written. Ship a file per language, or the other languages display raw keys.`,
    );
  }
  return result;
}

// ------------------------------------------------------------------------------------
// generate_decision_batch
// ------------------------------------------------------------------------------------

export function generateDecisionBatch(args = {}) {
  const prefix = asciiKey(requireString(args.prefix ?? args.file_prefix, 'prefix'), { fallback: 'mymod' });
  const decisions = requireArray(args.decisions, 'decisions');
  const language = assertLanguage(args.language ?? 'english');
  const withLocalisation = args.generate_localisation !== false;
  const dryRun = args.dry_run !== false;
  const outputRoot = optionalString(args.output_root);

  const blocks = [];
  const localisationEntries = [];

  for (const [index, decision] of decisions.entries()) {
    const key = requireDefinitionKey(decision.key ?? decision.id, `decisions[${index}].key`);
    const lines = [`${key} = {`];
    if (decision.owned_planets_only) lines.push('\towned_planets_only = yes');
    if (decision.sound) lines.push(`\tsound = ${optionalString(decision.sound)}`);
    lines.push(`\ticon = ${optionalString(decision.icon) ?? 'decision_resources'}`);
    if (decision.resources) {
      const costLines = Object.entries(decision.resources.cost ?? {}).map(
        ([resource, amount]) => `${resource} = ${Number(amount)}`,
      );
      lines.push('\tresources = {');
      lines.push(`\t\tcategory = ${optionalString(decision.resources.category) ?? 'decisions'}`);
      if (costLines.length > 0) {
        lines.push('\t\tcost = {', ...costLines.map((line) => `\t\t\t${line}`), '\t\t}');
      }
      lines.push('\t}');
    }
    if (decision.enactment_time !== undefined && decision.enactment_time !== null) {
      lines.push(`\tenactment_time = ${Number(decision.enactment_time)}`);
    }
    if (Array.isArray(decision.prerequisites) && decision.prerequisites.length > 0) {
      lines.push(`\tprerequisites = { ${quoteList(decision.prerequisites)} }`);
    }
    if (decision.show_tech_unlock_if) lines.push(block('show_tech_unlock_if', decision.show_tech_unlock_if, 1));
    lines.push(block('potential', decision.potential ?? 'always = yes', 1));
    if (decision.allow) lines.push(block('allow', decision.allow, 1));
    if (decision.on_queued) lines.push(block('on_queued', decision.on_queued, 1));
    if (decision.on_unqueued) lines.push(block('on_unqueued', decision.on_unqueued, 1));
    if (decision.abort_trigger) lines.push(block('abort_trigger', decision.abort_trigger, 1));
    if (decision.abort_effect) lines.push(block('abort_effect', decision.abort_effect, 1));
    lines.push(block('effect', requireString(decision.effect, `decisions[${index}].effect`), 1));
    if (decision.ai_weight) {
      lines.push(block('ai_weight', decision.ai_weight, 1));
    } else {
      lines.push('\tai_weight = {', '\t\tweight = 5', '\t}');
    }
    lines.push('}');
    blocks.push(lines.join('\n'));

    if (withLocalisation) {
      localisationEntries.push({
        key,
        value: requireString(decision.title ?? decision.name, `decisions[${index}].title`),
      });
      localisationEntries.push({
        key: `${key}_desc`,
        value: requireString(decision.description ?? decision.desc, `decisions[${index}].description`),
      });
    }
  }

  const scriptPath = `common/decisions/${prefix}_decisions.txt`;
  const content = `${SCRIPT_HEADER(scriptPath, 'common/decisions/example.txt')}${blocks.join('\n\n')}\n`;
  const files = [generatedFile(scriptPath, content, { summary: `${decisions.length} Stellaris decision(s)` })];
  if (withLocalisation) {
    files.push(
      localisationPlan({
        language,
        path: localisationPathFor(`${language}/${prefix}_decisions`, language),
        entries: localisationEntries,
        summary: 'Decision localisation',
      }),
    );
  }

  const result = finishGeneration({ dryRun, outputRoot, files });
  result.messages.push(
    'Decision fields follow the schema Stellaris ships in `common/decisions/example.txt`: owned_planets_only, sound, icon, resources, enactment_time, prerequisites, show_tech_unlock_if, potential, allow, on_queued, on_unqueued, abort_trigger, abort_effect, effect, ai_weight.',
  );
  result.messages.push(
    '`icon` names an icon under `gfx/interface/icons/decisions/`; a decision that references an icon that does not exist draws nothing.',
  );
  return result;
}

// ------------------------------------------------------------------------------------
// generate_civic_batch
// ------------------------------------------------------------------------------------

export function generateCivicBatch(args = {}) {
  const prefix = asciiKey(requireString(args.prefix ?? args.file_prefix, 'prefix'), { fallback: 'mymod' });
  const civics = requireArray(args.civics, 'civics');
  const language = assertLanguage(args.language ?? 'english');
  const withLocalisation = args.generate_localisation !== false;
  const dryRun = args.dry_run !== false;
  const outputRoot = optionalString(args.output_root);

  const blocks = [];
  const localisationEntries = [];

  for (const [index, civic] of civics.entries()) {
    const key = requireDefinitionKey(civic.key ?? civic.id, `civics[${index}].key`);
    const isOrigin = Boolean(civic.is_origin);
    const lines = [`${key} = {`];
    if (isOrigin) lines.push('\tis_origin = yes');
    lines.push(
      `\ticon = ${optionalString(civic.icon) ?? (isOrigin ? '"gfx/interface/icons/origins/origins_default.dds"' : '"gfx/interface/icons/civics/civic_default.dds"')}`,
    );
    // Origins and civics carry a picture: vanilla `origin_default` has
    // `picture = GFX_evt_metropolis`, used as the art in the origin tooltip.
    if (civic.picture) lines.push(`\tpicture = ${civic.picture}`);
    if (civic.playable) lines.push(block('playable', civic.playable, 1));
    lines.push(block('possible', civic.possible ?? '', 1));
    if (civic.potential) lines.push(block('potential', civic.potential, 1));
    lines.push(`\tdescription = ${optionalString(civic.description_key) ?? `${key}_desc`}`);
    if (civic.negative_description) lines.push(`\tnegative_description = ${civic.negative_description}`);
    if (civic.max_once_global) lines.push('\tmax_once_global = yes');
    if (civic.modifier) lines.push(block('modifier', civic.modifier, 1));
    lines.push('\trandom_weight = {');
    lines.push(`\t\tbase = ${Number(civic.random_weight ?? 0)}`);
    lines.push('\t}');
    lines.push('}');
    blocks.push(lines.join('\n'));

    if (withLocalisation) {
      localisationEntries.push({
        key,
        value: requireString(civic.title ?? civic.name, `civics[${index}].title`),
      });
      localisationEntries.push({
        key: `${key}_desc`,
        value: requireString(civic.description ?? civic.desc, `civics[${index}].description`),
      });
      if (civic.effects) localisationEntries.push({ key: `${key}_effects`, value: String(civic.effects) });
    }
  }

  const directory = 'common/governments/civics';
  const scriptPath = `${directory}/${prefix}_civics.txt`;
  const content = `${SCRIPT_HEADER(scriptPath, 'common/governments/civics/')}${blocks.join('\n\n')}\n`;
  const files = [generatedFile(scriptPath, content, { summary: `${civics.length} civic/origin definition(s)` })];
  if (withLocalisation) {
    files.push(
      localisationPlan({
        language,
        path: localisationPathFor(`${language}/${prefix}_civics`, language),
        entries: localisationEntries,
        summary: 'Civic and origin localisation',
      }),
    );
  }

  const result = finishGeneration({ dryRun, outputRoot, files });
  result.messages.push(
    'Civic and origin fields follow the shipped origin definitions: is_origin, icon (a texture path, not a token), playable, possible, potential, description (a localisation key), modifier, random_weight.',
  );
  result.messages.push(
    '`random_weight = { base = 0 }` keeps a non-player origin out of random empire generation, which is what vanilla does for origins only the AI should receive.',
  );
  return result;
}

// ------------------------------------------------------------------------------------
// generate_technology_batch
// ------------------------------------------------------------------------------------

export function generateTechnologyBatch(args = {}) {
  const prefix = asciiKey(requireString(args.prefix ?? args.file_prefix, 'prefix'), { fallback: 'mymod' });
  const technologies = requireArray(args.technologies, 'technologies');
  const language = assertLanguage(args.language ?? 'english');
  const withLocalisation = args.generate_localisation !== false;
  const dryRun = args.dry_run !== false;
  const outputRoot = optionalString(args.output_root);

  const blocks = [];
  const localisationEntries = [];

  for (const [index, tech] of technologies.entries()) {
    const key = requireDefinitionKey(tech.key ?? tech.id, `technologies[${index}].key`);
    const area = optionalString(tech.area) ?? 'society';
    if (!['physics', 'society', 'engineering'].includes(area)) {
      throw new ToolError(
        `technologies[${index}].area must be physics, society or engineering; received \`${area}\``,
      );
    }
    const lines = [`${key} = {`];

    if (tech.cost_modifier) {
      lines.push('\tcost = {');
      lines.push(`\t\tfactor = ${Number(tech.cost ?? 1000)}`);
      const body = blockBody('modifier', tech.cost_modifier, 3);
      lines.push('\t\tmodifier = {', body ?? '', '\t\t}');
      lines.push('\t}');
    } else {
      lines.push(`\tcost = ${Number(tech.cost ?? 1000)}`);
    }

    lines.push(`\tarea = ${area}`);
    if (tech.tier !== undefined && tech.tier !== null) lines.push(`\ttier = ${Number(tech.tier)}`);
    if (Array.isArray(tech.prerequisites) && tech.prerequisites.length > 0) {
      lines.push(`\tprerequisites = { ${tech.prerequisites.join(' ')} }`);
    }
    if (Array.isArray(tech.category) && tech.category.length > 0) {
      lines.push(`\tcategory = { ${tech.category.join(' ')} }`);
    }
    if (tech.is_rare) lines.push('\tis_rare = yes');
    if (tech.is_dangerous) lines.push('\tis_dangerous = yes');
    if (tech.start_tech) lines.push('\tstart_tech = yes');
    // The icon is a BARE sprite name (vanilla: `icon = "tech_cruisers"`); a path or a
    // quoted file will be reported as `Failed to find icon for technology: <key>`.
    // `inherit_icon` is only valid inside a technology_swap block, never at the top level.
    if (tech.icon) lines.push(`\ticon = ${optionalString(tech.icon)}`);    // Repeatable technologies use `levels = -1` plus `cost_per_level`; there is no
    // `is_repeatable` field in 4.1.7 (0 occurrences).
    if (tech.levels !== undefined && tech.levels !== null) lines.push(`\tlevels = ${Number(tech.levels)}`);
    if (tech.cost_per_level !== undefined && tech.cost_per_level !== null) {
      lines.push(`\tcost_per_level = ${Number(tech.cost_per_level)}`);
    }
    if (Array.isArray(tech.weight_groups) && tech.weight_groups.length > 0) {
      lines.push(`\tweight_groups = { ${tech.weight_groups.join(' ')} }`);
    }
    if (tech.mod_weight_if_group_picked) {
      const entries = Object.entries(tech.mod_weight_if_group_picked).map(
        ([group, factor]) => `${group} = ${Number(factor)}`,
      );
      lines.push('\tmod_weight_if_group_picked = {', ...entries.map((line) => `\t\t${line}`), '\t}');
    }
    if (Array.isArray(tech.feature_flags) && tech.feature_flags.length > 0) {
      lines.push('\tfeature_flags = {', ...tech.feature_flags.map((flag) => `\t\t${flag}`), '\t}');
    }
    if (tech.weight !== undefined && tech.weight !== null) lines.push(`\tweight = ${Number(tech.weight)}`);
    if (tech.weight_modifier) {
      const body = blockBody('weight_modifier', tech.weight_modifier, 2);
      lines.push('\tweight_modifier = {', body ?? '', '\t}');
    }
    if (tech.potential) lines.push(block('potential', tech.potential, 1));
    if (tech.modifier) lines.push(block('modifier', tech.modifier, 1));
    if (tech.ai_weight) lines.push(block('ai_weight', tech.ai_weight, 1));
    if (tech.gateway) lines.push(`\tgateway = ${optionalString(tech.gateway)}`);
    if (tech.technology_swap) {
      const swapLines = [];
      if (tech.technology_swap.name) swapLines.push(`\t\tname = ${tech.technology_swap.name}`);
      if (tech.technology_swap.inherit_icon !== undefined) {
        swapLines.push(`\t\tinherit_icon = ${tech.technology_swap.inherit_icon ? 'yes' : 'no'}`);
      }
      if (tech.technology_swap.inherit_effects !== undefined) {
        swapLines.push(`\t\tinherit_effects = ${tech.technology_swap.inherit_effects ? 'yes' : 'no'}`);
      }
      if (tech.technology_swap.trigger) {
        const body = blockBody('trigger', tech.technology_swap.trigger, 3);
        swapLines.push('\t\ttrigger = {', body ?? '', '\t\t}');
      }
      lines.push('\ttechnology_swap = {', ...swapLines, '\t}');
    }
    lines.push('}');
    blocks.push(lines.join('\n'));

    if (withLocalisation) {
      localisationEntries.push({
        key,
        value: requireString(tech.title ?? tech.name, `technologies[${index}].title`),
      });
      localisationEntries.push({
        key: `${key}_desc`,
        value: requireString(tech.description ?? tech.desc, `technologies[${index}].description`),
      });
    }
  }

  const directory = 'common/technology';
  const scriptPath = `${directory}/${prefix}_technology.txt`;
  const content = `${SCRIPT_HEADER(scriptPath, 'common/technology/000_documentation.txt')}${blocks.join('\n\n')}\n`;
  const files = [generatedFile(scriptPath, content, { summary: `${technologies.length} technology definition(s)` })];
  if (withLocalisation) {
    files.push(
      localisationPlan({
        language,
        path: localisationPathFor(`${language}/${prefix}_technology`, language),
        entries: localisationEntries,
        summary: 'Technology localisation',
      }),
    );
  }

  const result = finishGeneration({ dryRun, outputRoot, files });
  result.messages.push(
    'Technology fields follow `common/technology/000_documentation.txt` and the installed 4.1.7 files: cost (fixed or `{ factor, modifier }`), area, tier, prerequisites, category, is_rare, is_dangerous, levels, cost_per_level, weight_groups, mod_weight_if_group_picked, feature_flags, weight, weight_modifier, potential, modifier, technology_swap. `is_repeatable` is deliberately not generated: it does not occur in any 4.1.7 technology file, where repeatable research uses `levels = -1` with `cost_per_level` instead.',
  );
  result.messages.push(
    '`weight_modifier` uses `factor =` and `ai_weight` uses `factor =` or `base =` depending on the file type; a `factor = 0` followed by an `add` still adds, so use `set = 0` to exclude.',
  );
  return result;
}

// ------------------------------------------------------------------------------------
// generate_tradition_batch
// ------------------------------------------------------------------------------------

export function generateTraditionBatch(args = {}) {
  const prefix = asciiKey(requireString(args.prefix ?? args.file_prefix, 'prefix'), { fallback: 'mymod' });
  const language = assertLanguage(args.language ?? 'english');
  const withLocalisation = args.generate_localisation !== false;
  const dryRun = args.dry_run !== false;
  const outputRoot = optionalString(args.output_root);

  const traditions = Array.isArray(args.traditions) ? args.traditions : [];
  const ascensionPerks = Array.isArray(args.ascension_perks) ? args.ascension_perks : [];
  if (traditions.length === 0 && ascensionPerks.length === 0) {
    throw new ToolError('provide `traditions` and/or `ascension_perks`');
  }

  const files = [];
  const localisationEntries = [];

  if (traditions.length > 0) {
    const blocks = traditions.map((tradition, index) => {
      const key = requireDefinitionKey(tradition.key ?? tradition.id, `traditions[${index}].key`);
      const lines = [`${key} = {`];
      if (tradition.unlocks_agenda) lines.push(`\tunlocks_agenda = ${tradition.unlocks_agenda}`);
      if (tradition.custom_tooltip) lines.push(`\tcustom_tooltip = ${tradition.custom_tooltip}`);
      // Traditions have no `prerequisites` field in 4.1.7 (0 occurrences); gating is
      // done with `possible = { has_tradition = X }` (125 occurrences).
      if (tradition.possible) lines.push(block('possible', tradition.possible, 1));
      if (tradition.on_enabled) lines.push(block('on_enabled', tradition.on_enabled, 1));
      lines.push(block('modifier', requireString(tradition.modifier, `traditions[${index}].modifier`), 1));
      lines.push(
        block(
          'ai_weight',
          tradition.ai_weight ?? 'factor = 1000',
          1,
        ),
      );
      lines.push('}');
      if (withLocalisation) {
        localisationEntries.push({
          key,
          value: requireString(tradition.title ?? tradition.name, `traditions[${index}].title`),
        });
        // `common/traditions/99_README_TRADITIONS.txt` is explicit: a tradition's description
        // key is the tradition key plus `_delayed`, not `_desc`. `_desc` is the ascension
        // perk convention. Verified in 4.4.6: tr_logistics_1 -> tr_logistics_1_delayed.
        localisationEntries.push({
          key: `${key}_delayed`,
          value: requireString(tradition.description ?? tradition.desc, `traditions[${index}].description`),
        });
      }
      return lines.join('\n');
    });
    const scriptPath = `common/traditions/${prefix}_traditions.txt`;
    files.push(
      generatedFile(
        scriptPath,
        `${SCRIPT_HEADER(scriptPath, 'common/traditions/')}${blocks.join('\n\n')}\n`,
        { summary: `${traditions.length} tradition(s)` },
      ),
    );
  }

  if (ascensionPerks.length > 0) {
    const blocks = ascensionPerks.map((perk, index) => {
      const key = requireDefinitionKey(perk.key ?? perk.id, `ascension_perks[${index}].key`);
      const lines = [`${key} = {`];
      // Ascension perks have no `prerequisites` field either (0 occurrences in
      // `common/ascension_perks/`); `potential` (50) and `possible` (34) do the gating.
      if (perk.potential) lines.push(block('potential', perk.potential, 1));
      if (perk.possible) lines.push(block('possible', perk.possible, 1));
      if (perk.on_enabled) lines.push(block('on_enabled', perk.on_enabled, 1));
      if (perk.modifier) lines.push(block('modifier', perk.modifier, 1));
      lines.push('}');
      if (withLocalisation) {
        localisationEntries.push({
          key,
          value: requireString(perk.title ?? perk.name, `ascension_perks[${index}].title`),
        });
        localisationEntries.push({
          key: `${key}_desc`,
          value: requireString(perk.description ?? perk.desc, `ascension_perks[${index}].description`),
        });
      }
      return lines.join('\n');
    });
    const scriptPath = `common/ascension_perks/${prefix}_ascension_perks.txt`;
    files.push(
      generatedFile(
        scriptPath,
        `${SCRIPT_HEADER(scriptPath, 'common/ascension_perks/')}${blocks.join('\n\n')}\n`,
        { summary: `${ascensionPerks.length} ascension perk(s)` },
      ),
    );
  }

  if (withLocalisation && localisationEntries.length > 0) {
    files.push(
      localisationPlan({
        language,
        path: localisationPathFor(`${language}/${prefix}_traditions`, language),
        entries: localisationEntries,
        summary: 'Tradition and ascension perk localisation',
      }),
    );
  }

  const result = finishGeneration({ dryRun, outputRoot, files });
  result.messages.push(
    'Traditions and ascension perks are registered by the definition key itself; a tradition tree also needs an entry in `common/tradition_categories/` before the game shows it, which this tool does not generate.',
  );
  result.messages.push(
    'Neither traditions nor ascension perks have a `prerequisites` field in 4.1.7 (0 occurrences in both folders). Gate them with `possible = { has_tradition = X }` or `potential`, which this generator accepts as raw script bodies.',
  );
  return result;
}
